name: Deploy to vps (prod)

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 200.234.227.69
          port: 2222
          username: gaston
          key: ${{ secrets.PRIVATE_KEY_PROD }}
          script: "cd /var/www/html/compost/; ./.scripts/prod.sh"
