name: Deploy to vps

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 161.22.47.18
          port: 2222
          username: icesito
          key: ${{ secrets.PRIVATE_KEY }}
          script: "cd /var/www/html/compost; git pull origin dev; php artisan route:clear; sudo service php8.3-fpm reload;npm run build"
